// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJb7sZZ-lxUVxf8llRXBjNZKo5PczCE5g',
    appId: '1:446732435291:web:1e4b20353024fb51c7a47e',
    messagingSenderId: '446732435291',
    projectId: 'flutter-biblioteca-app',
    authDomain: 'flutter-biblioteca-app.firebaseapp.com',
    storageBucket: 'flutter-biblioteca-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjhbRJYFQMluJS9yt86a30VtB1RLO_aM',
    appId: '1:446732435291:android:612c1b9c97143b12c7a47e',
    messagingSenderId: '446732435291',
    projectId: 'flutter-biblioteca-app',
    storageBucket: 'flutter-biblioteca-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrpbWc9Bhbsn8JXrIlBFcn7xluKlV9QmI',
    appId: '1:446732435291:ios:6b97de0d223fe170c7a47e',
    messagingSenderId: '446732435291',
    projectId: 'flutter-biblioteca-app',
    storageBucket: 'flutter-biblioteca-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterBiblioteca',
  );

}